export default [
  {
    appId: 2,
    checked: false,
    children: null,
    code: "index",
    createTime: "2020-12-17 10:29:34",
    danger: false,
    icon: "",
    id: 734,
    level: 1,
    name: "首页",
    order: 65,
    path: "",
    pid: 0,
    remark: "首页",
    type: "MENU",
    updateTime: "2020-12-17 10:33:38"
  },
  {
    appId: 2,
    checked: false,
    children: [
      {
        appId: 2,
        checked: false,
        children: null,
        code: "estimate_long_period_task",
        createTime: "2021-04-30 09:38:38",
        danger: false,
        icon: "",
        id: 8440,
        level: 2,
        name: "长周期预估",
        order: 0,
        path: "EstimateLongPeriodTask",
        pid: 8439,
        remark: "预估呈现",
        type: "MENU",
        updateTime: "2021-07-08 11:03:24"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "strategic_kpi_monthPredictTabs",
        createTime: "2020-12-18 11:36:32",
        danger: false,
        icon: "",
        id: 793,
        level: 2,
        name: "月度预估",
        order: 1,
        path: "operateApplyMoney",
        pid: 8439,
        remark: "预估呈现",
        type: "MENU",
        updateTime: "2021-07-08 16:06:09"
      }
    ],
    code: "predict",
    createTime: "2021-04-30 09:36:13",
    danger: false,
    icon: "iconpingtaizonglancopy",
    id: 8439,
    level: 1,
    name: "预估",
    order: 70,
    path: "",
    pid: 0,
    remark: "预估呈现",
    type: "MENU",
    updateTime: "2021-07-08 14:20:36",
    remarkList: ["预估呈现"]
  },
  {
    appId: 2,
    checked: false,
    children: [
      {
        appId: 2,
        checked: false,
        children: null,
        code: "strategic_activity_center_actList",
        createTime: "2020-12-18 10:49:56",
        danger: false,
        icon: "",
        id: 752,
        level: 2,
        name: "2C活动中心",
        order: 1,
        path: "actList",
        pid: 12081,
        remark: "2C活动",
        type: "MENU",
        updateTime: "2021-07-08 11:35:01"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "tc_act_list",
        createTime: "2021-04-26 13:47:26",
        danger: false,
        icon: "",
        id: 8422,
        level: 2,
        name: "2C活动统筹",
        order: 2,
        path: "tcActList",
        pid: 12081,
        remark: "2C活动",
        type: "MENU",
        updateTime: "2021-07-08 11:33:50"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "act_settings",
        createTime: "2021-06-21 10:27:26",
        danger: false,
        icon: "",
        id: 10162,
        level: 2,
        name: "2C活动配置",
        order: 3,
        path: "wordsSettings",
        pid: 12081,
        remark: "2C活动",
        type: "MENU",
        updateTime: "2021-07-08 11:35:09"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "strategic_act_estimate_2BEstimateTask",
        createTime: "2020-12-18 11:23:21",
        danger: false,
        icon: "",
        id: 773,
        level: 2,
        name: "2B活动中心",
        order: 4,
        path: "2BEstimateTask",
        pid: 12081,
        remark: "2B活动",
        type: "MENU",
        updateTime: "2021-07-08 11:35:25"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "strategic_act_estimate_2BEstimateOperation",
        createTime: "2020-12-18 11:22:58",
        danger: false,
        icon: "",
        id: 772,
        level: 2,
        name: "2B活动统筹",
        order: 5,
        path: "2BEstimateOperation",
        pid: 12081,
        remark: "2B活动",
        type: "MENU",
        updateTime: "2021-07-08 11:35:42"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "prepack_Plan_tab",
        createTime: "2021-07-29 09:56:44",
        danger: false,
        icon: "",
        id: 14287,
        level: 2,
        name: "预包计划",
        order: 6,
        path: "prepackPlanTab",
        pid: 12081,
        remark: "活动预包",
        type: "MENU",
        updateTime: "2021-08-06 09:24:46"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "uppack_plan_tab",
        createTime: "2021-07-21 13:32:00",
        danger: false,
        icon: "",
        id: 13082,
        level: 2,
        name: "拆包计划",
        order: 7,
        path: "uppackPlanTab",
        pid: 12081,
        remark: "活动预包",
        type: "MENU",
        updateTime: "2021-07-21 13:32:00"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "prepack_inventory",
        createTime: "2021-09-02 14:05:37",
        danger: false,
        icon: "",
        id: 16794,
        level: 2,
        name: "预包库存",
        order: 8,
        path: "prepackInventory",
        pid: 12081,
        remark: "活动预包",
        type: "MENU",
        updateTime: "2021-09-02 14:05:37"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "prepack_set_menu",
        createTime: "2021-07-19 16:08:55",
        danger: false,
        icon: "",
        id: 12551,
        level: 2,
        name: "预包配置",
        order: 9,
        path: "prepackSetMenu",
        pid: 12081,
        remark: "活动预包",
        type: "MENU",
        updateTime: "2021-07-19 16:08:55"
      }
    ],
    code: "activity",
    createTime: "2021-07-08 10:54:11",
    danger: false,
    icon: "iconhuodong",
    id: 12081,
    level: 1,
    name: "活动",
    order: 71,
    path: "",
    pid: 0,
    remark: "2C活动,2B活动,活动预包",
    type: "MENU",
    updateTime: "2021-07-19 16:07:59",
    remarkList: ["2C活动", "2B活动", "活动预包"]
  },
  {
    appId: 2,
    checked: false,
    children: [
      {
        appId: 2,
        checked: false,
        children: null,
        code: "strategic_prepackaged_plan",
        createTime: "2020-12-18 11:28:34",
        danger: false,
        icon: "",
        id: 777,
        level: 2,
        name: "预包计划",
        order: 0,
        path: "prepackagedPlan",
        pid: 742,
        remark: "",
        type: "MENU",
        updateTime: "2021-07-08 11:19:16"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "strategic_activity_purchase",
        createTime: "2020-12-18 10:54:45",
        danger: false,
        icon: "",
        id: 757,
        level: 2,
        name: "选品分仓设置",
        order: 1,
        path: "purchase",
        pid: 742,
        remark: "",
        type: "MENU",
        updateTime: "2021-07-08 11:23:16"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "strategic_daily_goods_reserve",
        createTime: "2020-12-18 11:27:33",
        danger: false,
        icon: "",
        id: 776,
        level: 2,
        name: "日常商品预留",
        order: 1,
        path: "dailyGoodsReserve",
        pid: 742,
        remark: "",
        type: "MENU",
        updateTime: "2020-12-18 11:27:33"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "strategic_automatic_setting",
        createTime: "2020-12-18 11:29:20",
        danger: false,
        icon: "",
        id: 778,
        level: 2,
        name: "预打包配置",
        order: 3,
        path: "automaticSetTab",
        pid: 742,
        remark: "",
        type: "MENU",
        updateTime: "2021-07-28 11:35:01"
      }
    ],
    code: "prepack",
    createTime: "2020-12-18 10:41:37",
    danger: false,
    icon: "iconpack",
    id: 742,
    level: 1,
    name: "预包",
    order: 75,
    path: "",
    pid: 0,
    remark: "",
    type: "MENU",
    updateTime: "2021-07-08 11:17:22",
    remarkList: [""]
  },
  {
    appId: 2,
    checked: false,
    children: [
      {
        appId: 2,
        checked: false,
        children: null,
        code: "qc_shop_info_set",
        createTime: "2021-06-08 10:38:45",
        danger: false,
        icon: "",
        id: 10060,
        level: 2,
        name: "质检店铺建档",
        order: 0,
        path: "qcShopInfoSet",
        pid: 743,
        remark: "配置",
        type: "MENU",
        updateTime: "2021-07-08 11:41:13"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "qc_ad_ban_words",
        createTime: "2021-07-08 13:58:51",
        danger: false,
        icon: "",
        id: 12098,
        level: 2,
        name: "广告法违禁词",
        order: 1,
        path: "adLawBanWordTab",
        pid: 743,
        remark: "配置",
        type: "MENU",
        updateTime: "2021-07-08 16:04:48"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "ad_law_list",
        createTime: "2021-04-26 12:16:18",
        danger: false,
        icon: "",
        id: 8420,
        level: 2,
        name: "天猫日常质检",
        order: 2,
        path: "qcTmallDailyMenu",
        pid: 743,
        remark: "天猫",
        type: "MENU",
        updateTime: "2021-09-10 16:08:31"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "tmall_big_sale_menu",
        createTime: "2021-09-10 09:18:20",
        danger: false,
        icon: "",
        id: 16966,
        level: 2,
        name: "天猫大促质检",
        order: 13,
        path: "qcTmallBigSaleMenu",
        pid: 743,
        remark: "天猫",
        type: "MENU",
        updateTime: "2021-09-14 17:52:39"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "qc_tiktok_daily",
        createTime: "2021-07-08 16:03:44",
        danger: false,
        icon: "",
        id: 12112,
        level: 2,
        name: "抖音日常质检",
        order: 14,
        path: "tikTokDailyMenu",
        pid: 743,
        remark: "抖音",
        type: "MENU",
        updateTime: "2021-07-12 15:04:40"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "strategic_activity_priceMonitor",
        createTime: "2020-12-18 11:23:45",
        danger: false,
        icon: "",
        id: 774,
        level: 2,
        name: "底价监控",
        order: 15,
        path: "priceMonitor",
        pid: 743,
        remark: "猫超",
        type: "MENU",
        updateTime: "2020-12-18 11:23:45"
      }
    ],
    code: "qc",
    createTime: "2020-12-18 10:42:27",
    danger: false,
    icon: "iconfont iconquality",
    id: 743,
    level: 1,
    name: "质检",
    order: 76,
    path: "",
    pid: 0,
    remark: "配置，天猫，抖音，猫超",
    type: "MENU",
    updateTime: "2021-07-08 14:34:50",
    remarkList: ["配置", "天猫", "抖音", "猫超"]
  },
  {
    appId: 2,
    checked: false,
    children: [
      {
        appId: 2,
        checked: false,
        children: null,
        code: "strategic_activity_predictiveCheck_predictiveCheckTabs",
        createTime: "2020-12-18 11:10:58",
        danger: false,
        icon: "",
        id: 765,
        level: 2,
        name: "预估校验",
        order: 0,
        path: "predictiveCheckTabs",
        pid: 12082,
        remark: "活动监控",
        type: "MENU",
        updateTime: "2020-12-18 11:10:58"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "strategic_activity_prepack_prepackTabs",
        createTime: "2020-12-18 11:20:41",
        danger: false,
        icon: "",
        id: 768,
        level: 2,
        name: "预包监控",
        order: 1,
        path: "prepackTabs",
        pid: 12082,
        remark: "预包监控",
        type: "MENU",
        updateTime: "2020-12-18 11:20:41"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "prepack_monitor_menu",
        createTime: "2021-08-23 14:26:15",
        danger: false,
        icon: "",
        id: 15964,
        level: 2,
        name: "新预包监控",
        order: 2,
        path: "prepackMonitorMenu",
        pid: 12082,
        remark: "预包监控",
        type: "MENU",
        updateTime: "2021-08-23 14:26:15"
      }
    ],
    code: "monitor",
    createTime: "2021-07-08 10:55:40",
    danger: false,
    icon: "iconxitong6",
    id: 12082,
    level: 1,
    name: "监控",
    order: 77,
    path: "",
    pid: 0,
    remark: "活动监控，预包监控",
    type: "MENU",
    updateTime: "2021-07-08 16:30:46",
    remarkList: ["活动监控", "预包监控"]
  },
  {
    appId: 2,
    checked: false,
    children: [
      {
        appId: 2,
        checked: false,
        children: null,
        code: "ep_op_log",
        createTime: "2021-06-29 11:31:17",
        danger: false,
        icon: "",
        id: 10286,
        level: 2,
        name: "运营日志",
        order: 0,
        path: "opLog",
        pid: 10285,
        remark: "",
        type: "MENU",
        updateTime: "2021-06-29 11:31:38"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "strategic_kpi_orderPredictAccuracy",
        createTime: "2020-12-18 11:37:29",
        danger: false,
        icon: "",
        id: 795,
        level: 2,
        name: "预估准确率",
        order: 1,
        path: "orderPredictAccuracy",
        pid: 10285,
        remark: "",
        type: "MENU",
        updateTime: "2020-12-18 11:37:29"
      }
    ],
    code: "ep_review",
    createTime: "2021-06-29 11:30:57",
    danger: false,
    icon: "iconxitong1",
    id: 10285,
    level: 1,
    name: "复盘",
    order: 78,
    path: "",
    pid: 0,
    remark: "",
    type: "MENU",
    updateTime: "2021-07-08 16:31:52",
    remarkList: [""]
  },
  {
    appId: 2,
    checked: false,
    children: [
      {
        appId: 2,
        checked: false,
        children: null,
        code: "home_page_setting",
        createTime: "2021-06-30 10:32:53",
        danger: false,
        icon: "",
        id: 10307,
        level: 2,
        name: "首页配置",
        order: 0,
        path: "homePageSetting",
        pid: 9886,
        remark: "",
        type: "MENU",
        updateTime: "2021-06-30 10:32:53"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "alert_setting",
        createTime: "2021-05-17 16:56:12",
        danger: false,
        icon: "",
        id: 8917,
        level: 2,
        name: "预警配置",
        order: 1,
        path: "alertSetting",
        pid: 9886,
        remark: "",
        type: "MENU",
        updateTime: "2021-05-17 16:56:12"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "log_options",
        createTime: "2021-05-31 14:06:59",
        danger: false,
        icon: "",
        id: 9887,
        level: 2,
        name: "日志配置",
        order: 1,
        path: "opLogOptions",
        pid: 9886,
        remark: "",
        type: "MENU",
        updateTime: "2021-05-31 14:06:59"
      }
    ],
    code: "operation_log",
    createTime: "2021-05-31 14:05:44",
    danger: false,
    icon: "iconxitong",
    id: 9886,
    level: 1,
    name: "系统",
    order: 84,
    path: "",
    pid: 0,
    remark: "",
    type: "MENU",
    updateTime: "2021-07-08 14:37:27",
    remarkList: [""]
  },
  {
    appId: 2,
    checked: false,
    children: [
      {
        appId: 2,
        checked: false,
        children: [
          {
            appId: 2,
            checked: false,
            children: null,
            code: "dic_overall_set",
            createTime: "2020-12-18 11:31:12",
            danger: false,
            icon: "",
            id: 781,
            level: 3,
            name: "质检详情设置",
            order: 0,
            path: "overallSet",
            pid: 780,
            remark: "",
            type: "MENU",
            updateTime: "2020-12-18 11:31:12"
          },
          {
            appId: 2,
            checked: false,
            children: null,
            code: "dic_common_progress",
            createTime: "2020-12-18 11:31:35",
            danger: false,
            icon: "",
            id: 782,
            level: 3,
            name: "报名进度查看",
            order: 1,
            path: "overallProgress",
            pid: 780,
            remark: "",
            type: "MENU",
            updateTime: "2021-01-14 11:21:49"
          },
          {
            appId: 2,
            checked: false,
            children: null,
            code: "dic_overall_whitelist",
            createTime: "2020-12-18 11:31:56",
            danger: false,
            icon: "",
            id: 783,
            level: 3,
            name: "白名单管理",
            order: 2,
            path: "overallWhitelist",
            pid: 780,
            remark: "",
            type: "MENU",
            updateTime: "2021-01-14 11:22:00"
          },
          {
            appId: 2,
            checked: false,
            children: null,
            code: "dic_overall_result",
            createTime: "2021-01-14 17:52:21",
            danger: false,
            icon: "",
            id: 2321,
            level: 3,
            name: "质检结果查看",
            order: 3,
            path: "overallResult",
            pid: 780,
            remark: "",
            type: "MENU",
            updateTime: "2021-01-14 17:52:21"
          }
        ],
        code: "dic_overall",
        createTime: "2020-12-18 11:30:47",
        danger: false,
        icon: "",
        id: 780,
        level: 2,
        name: "统筹大促质检",
        order: 0,
        path: "",
        pid: 12083,
        remark: "质检管理",
        type: "MENU",
        updateTime: "2020-12-18 11:30:47"
      },
      {
        appId: 2,
        checked: false,
        children: [
          {
            appId: 2,
            checked: false,
            children: null,
            code: "dic_daily_result",
            createTime: "2020-12-18 11:33:29",
            danger: false,
            icon: "",
            id: 786,
            level: 3,
            name: "日常质检",
            order: 0,
            path: "dailyResult",
            pid: 785,
            remark: "",
            type: "MENU",
            updateTime: "2020-12-18 11:33:29"
          },
          {
            appId: 2,
            checked: false,
            children: null,
            code: "dic_daily_common",
            createTime: "2020-12-18 11:33:52",
            danger: false,
            icon: "",
            id: 787,
            level: 3,
            name: "聚划算/淘抢购",
            order: 1,
            path: "dailyCommon",
            pid: 785,
            remark: "",
            type: "MENU",
            updateTime: "2020-12-18 11:33:52"
          },
          {
            appId: 2,
            checked: false,
            children: null,
            code: "dic_daily_promotion",
            createTime: "2020-12-18 11:34:19",
            danger: false,
            icon: "",
            id: 788,
            level: 3,
            name: "非统筹官方活动",
            order: 2,
            path: "dailyPromotion",
            pid: 785,
            remark: "",
            type: "MENU",
            updateTime: "2020-12-18 11:34:19"
          }
        ],
        code: "dic_daily",
        createTime: "2020-12-18 11:33:01",
        danger: false,
        icon: "",
        id: 785,
        level: 2,
        name: "店铺日常质检",
        order: 1,
        path: "",
        pid: 12083,
        remark: "质检管理",
        type: "MENU",
        updateTime: "2020-12-18 11:33:01"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "qc_log",
        createTime: "2021-01-22 14:58:59",
        danger: false,
        icon: "",
        id: 3117,
        level: 2,
        name: "日志统计",
        order: 2,
        path: "qcLog",
        pid: 12083,
        remark: "质检管理",
        type: "MENU",
        updateTime: "2021-01-22 14:58:59"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "strategic_kpi_orderFacilityScale",
        createTime: "2020-12-18 11:37:01",
        danger: false,
        icon: "",
        id: 794,
        level: 2,
        name: "订单分仓比设置",
        order: 3,
        path: "orderFacilityScale",
        pid: 12083,
        remark: "系统设置",
        type: "MENU",
        updateTime: "2021-07-15 19:45:41"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "strategic_kpi_salePredictTabsMonthlyPredict",
        createTime: "2020-12-18 11:36:11",
        danger: false,
        icon: "",
        id: 792,
        level: 2,
        name: "销售/请款预估查看",
        order: 4,
        path: "salePredictTabsMonthlyPredict",
        pid: 12083,
        remark: "KPI管理",
        type: "MENU",
        updateTime: "2020-12-18 11:36:11"
      },
      {
        appId: 2,
        checked: false,
        children: null,
        code: "kpi_monthPredict",
        createTime: "2021-07-08 15:47:43",
        danger: false,
        icon: "",
        id: 12111,
        level: 2,
        name: "月度目标预估",
        order: 5,
        path: "monthPredictTabs",
        pid: 12083,
        remark: "KPI管理",
        type: "MENU",
        updateTime: "2021-07-08 16:02:00"
      }
    ],
    code: "old_version",
    createTime: "2021-07-08 11:01:53",
    danger: false,
    icon: "icongongneng",
    id: 12083,
    level: 1,
    name: "旧版",
    order: 85,
    path: "",
    pid: 0,
    remark: "质检管理，KPI管理，系统设置",
    type: "MENU",
    updateTime: "2021-07-08 16:33:14",
    remarkList: ["质检管理", "系统设置", "KPI管理"]
  }
]
